const data = {
  products: [
    {
      name: 'Netplay Slim Shirt',
      slug: 'netplay-slim-shirt',
      category: 'shirt',
      Image: '/images/p1.jpg',
      price: '$20',
      countInstock: 10,
      brand: 'Netplay',
      rating: 10,
      numReviews: 10,
      description: 'Best quality shirt',
    },
    {
      name: 'NorthRepublic Slim Shirt',
      slug: 'north-republic-slim-shirt',
      category: 'shirt',
      Image: '/images/p2.jpg',
      price: '$15',
      countInstock: 9,
      brand: 'NorthRepublic',
      rating: 9,
      numReviews: 10,
      description: 'Best quality shirt',
    },
    {
      name: `Levi's pant`,
      slug: `Levi's-pant`,
      category: 'pant',
      Image: '/images/p3.jpg',
      price: '$60',
      countInstock: 10,
      brand: `Levi's`,
      rating: 10,
      numReviews: 10,
      description: 'Best quality pant',
    },
    {
      name: 'IndianGarage pant',
      slug: 'indian-garage-pant',
      category: 'pant',
      Image: '/images/p4.jpg',
      price: '$50',
      countInstock: 10,
      brand: 'IndianGarage',
      rating: 10,
      numReviews: 10,
      description: 'Best quality pant',
    },
  ],
};
export default data;
